# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:            DJ José Sanchez
baseurl:          "/" # the subpath of your site, e.g. /blog
url:              "http://www.djsanchez.eu" # the base hostname & protocol for your site, e.g. http://example.com
timezone:         "Europe/Luxembourg"
google_api_key:   "AIzaSyAb9vgRqufy200BAaulAakY1eGegpGp4eM"

# Build settings
markdown:         kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
collections:
  events :
      output:     true
      permalink:  /:collection/:path/
  albums :
      output :    true
      permalink:  /:collection/:path/
defaults:
    - scope :
        path:     ""
        type:     "events"
      values:
        layout:   "event"
        is_event: true
    - scope :
        path:     ""
        type:     "albums"
      values:
        layout:   "album"
        is_album : true

pagination:
    enabled:      false
    collection:   ['posts', 'events']
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
