# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:              DJ José Sanchez
baseurl:            "/" # the subpath of your site, e.g. /blog
url:                "http://www.djsanchez.eu" # the base hostname & protocol for your site, e.g. http://example.com
timezone:           "Europe/Luxembourg"
google_api_key:     "AIzaSyBtYUCV9vOHWUXtS7Vb7PW34c1jSmGDR1A"
social:
  facebook:       https://www.facebook.com/DJ.J.Sanchez/
  twitter:        sanchezjosedj
  instagram:      dj_josesanchez

# Build settings
sass:
  sass_dir:       _sass
markdown:           kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
collections:
  posts:
    output: true
    permalink: /blog/:path/
  events :
    output:       true
    permalink:    /:collection/:path/
  albums :
      output :      true
      permalink:    /:collection/:path/
defaults:
- scope :
    path:       ""
    type:       "events"
  values:
    layout:     "event"
    is_event:   true
- scope :
    path:       ""
    type:       "albums"
  values:
    layout:     "album"
    is_album :  true

pagination:
  enabled:        true
podcast:
  title: "L'Essentiel Mix - L'émission Club par José Sanchez"
  description: Chaque samedi soir, l'Essentiel Radio boost ton week-end, retrouve l'Essentiel Mix, l'émission qui va désormais changer ton week-end. 22h - 00h, il a mixé avec Lost Frequencies, Kungs et tout les plus grands. En exclusivité, DJ José Sanchez a choisis l'Essentiel Radio pour sa nouvelle résidence. L'Essentiel Mix, l'émission club de référence au Luxembourg, c'est sur l'Essentiel.
  url: /podcast.xml # podcast xml url
  author: DJ José Sanchez
  email: contact@djsanchez.eu
  logo: https://d2f4gvquo0w67t.cloudfront.net/podcast.jpg # logo in 1400 – 3000 pixel
  language: fr-fr # http://www.loc.gov/standards/iso639-2/php/code_list.php (ie. 'en-us')
  category: Music # https://help.apple.com/itc/podcasts_connect/#/itc9267a2f12
  subcategory:
  type: episodic # episodic | serial
  explicit: false # true (must be true if at least one episode is explicit) | false
  complete: 'no' # 'yes' | 'no'
  block: 'no' # 'yes' (hide in Apple’s directory) | 'no'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
