backend:
  name:                           git-gateway
  accept_roles:                   [admin,editor]
  branch:                         master # Branch to update (optional; defaults to master)

site_url:                         https://djsanchez.eu
logo_url:                         https://djsanchez.eu/assets/img/logo/logo.png
# This line should *not* be indented
# publish_mode:                   editorial_workflow
# This line should *not* be indented
media_folder:                     "uploads" # Media files will be stored in the repo under images/uploads

collections:
    - name:                       "pages"
      label:                      "Pages & Config"
      sort:                       "title:asc"
      files:
          - name:                 "videos"
            label:                "Videos"
            file:                 "_data/videos.yml"
            fields:
                - label:          "Videos"
                  name:           "videos-links"
                  widget:         "list"
                  field: { label: "Video Link", name: "url", widget: "string", hint: "Plese only youtube video at the moment."}
          - label:                "Biography Page"
            name:                 "biography"
            file:                 "biography.md"
            fields:
                - { label: 'Title', name: 'title', default: 'Biography' }
                - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
                - { label: 'Body', name: 'body', widget: 'markdown' }
                - { label: 'Signature Picture', name: 'signature_picture', widget: 'image', required: false, allow_multiple: false }
                - { label: 'Background Picture', name: 'background_picture', widget: 'image', required: false, allow_multiple: false , hint: "Should be 1920 x 1080 or same ratio. Will be cropped otherwise."}
          - label:                "Contact Page"
            name:                 "contact"
            file:                 "contact.md"
            fields:
                - { label: 'Title', name: 'title', default: 'Contact' }
                - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'contact' }
                - { label: 'This is contact page', name: 'is_contact', widget: 'hidden', default: 'true' }
                - label:          'Contact informations'
                  name:           'contact_info'
                  widget:         'object'
                  fields:
                      - {label: "Street Address", name: "address", widget: "string"}
                      - {label: "Email", name: "email", widget: "string"}
                      - {label: "Phone", name: "phone", widget: "string"}
                      - {label: "Fax", name: "fax", widget: "string"}
                      - {label: "Description", name: "description", widget: "markdown"}
                      - {label: "GPS coordinates for the map", name: "gps", widget: "map"}
                - { label: 'Body', name: 'body', widget: 'markdown' }
    - name: "podcasts"
      label: "Podcasts episodes"
      folder: "_posts"
      create: true
      sort: "date:desc"
      editor:
        preview: false
      summary: "{{title}} - {{type}}"
      slug:                       "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
      fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "podcast"}
          - {label: "Category", name: "category", widget: "hidden", default: "podcast"}
          - {label: "Season", name: "season", widget: "number", min: 1, step: 1, value_type: "int", default: 1, required: true}
          - {label: "Episode", name: "episode", widget: "number", min: 1, step: 1, value_type: "int", default: 1, required: true}
          - {label: "Title", name: "title", widget: "string", required: true}
          - {lavel: "File", name: "audio", widget: "string", required: true, pattern: ['/^https?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&\/=]*)$/', "Must be a valid URL"], default: "https://d2f4gvquo0w67t.cloudfront.net/"}
          - {label: "Explicit Content", name: "explicit", widget: "boolean", default: false, hint: "Does it include swearing or porn references"}
          - {label: "Episode Type", name: "episodetype", required: true, widget: "select", options: ["full", "trailer", "bonus"], default: ["full"]}
          - {label: "Duration (in seconds)", name: "length", widget: "number", min: 1, step: 1, value_type: "int", default: 1, required: true}
          - {label: "Author", name: "author", widget: "string", required: true, default: "Dj José Sanchez"}

    - name:                       "albums"
      label:                      "Music Albums"
      folder:                     "_albums"
      create:                     true
      sort:                       "date:desc"
      editor:
        preview:                  false
      summary:                    "{{title}} - {{type}}"
      slug:                       "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
      fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "album"}
          - {label: "Release Date", name: "date", widget: "date"}
          - {label: "Catalog", name: "Catalog", widget: "string", required: false}
          - {label: "Label", name: "label", widget: "string", required: false}
          - {label: "Album Title", name: "title", widget: "string", hint: "Or track title if you'll publish just a single track."}
          - label:                "Type"
            name:                 "type"
            widget:               "select"
            options:              ["Live Set","Podcast","Promo Set", "Remix", "Mashup", "Original"]
            default:              ["Live Set"]
          - label:                "Format"
            name:                 "format"
            widget:               "select"
            options:              ["Vynil","CD","Digital", "Streaming"]
            default:              ["Streaming"]
          - label:                "Tracks"
            name:                 "tracks"
            widget:               "list"
            required:             false
            fields:
                - label:          "Name"
                  name:           "name"
                  widget:         "string"
                - label:          "Duration"
                  name:           "duration"
                  widget:         "string"
                  hint:           "Format xx:xx"
                - labal:          "Track"
                  name:           "file"
                  widget:         "file"
                  allow_multiple: false
                  required:       false
          - label:                "Links to distributions platforms"
            name:                 "links"
            widget:               "list"
            hint:                 "Please only add one url per platform."
            fields:
                - label:          "Platform"
                  name:           "platform"
                  widget:         "select"
                  options:        ["lastfm","soundcloud","itunes","spotify","amazon"]
                  default:        ["soundcloud"]
                  hint:           "Select the platform associated with the url"
                - {label: "URL", name: "url", widget: "string"}
          - {label: "Cover Picture", name: "picture", widget: "image", allow_multiple: false}
          - {label: "Background Picture", name: "background_picture", widget: "image", allow_multiple: false, required: false, hint: "1920x1080 picture. Will be cropped"}
